### ISSUE TITLE
Pilot equipment and space in Rotary/Fixed wing

### ISSUE THREAD

**Issue by kavinsky** [11thmeu/addons#8]
- [ ] Remove backpacks and move to ground on getIn Aircrafts (Rotary/Fixed)
- [ ] Remove Primary/Launcher weapons on getIn Fixed Wing aircrafts
- [ ] Pilots can hold sidearm
- [ ] Limit space on Pilot vest/suit
- [ ] Make suit flame retardant

Linked with #5

**Comment by Thraxs** [comment]
Backpacks and weapons cant be dropped to the ground in the GetIn event handler i think. Using the action its executed after you get out of the vehicle and the gear cant be removed and added again with scripting commands because they would not match perfectly. ACE2 did the weapons because they didnt have custom attachments and backpacks because they were a custom ruck system.

**Comment by kavinsky** [comment]
alternative? kick the pilot?

**Comment by kavinsky** [comment]
mass closing
